version: '3.8'
services: 
  midas-db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "${MYSQL_RANDOM_ROOT_PASSWORD}"
    ports: 
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - midas-net
  
  midas-app:
    container_name: app
    entrypoint: ["sh", "-c", "npm install && npm run build && npm run start"]
    build: .
    ports: 
      - 3000:3000
    networks:
      - midas-net

networks:
  midas-net:
    driver: bridge

volumes:
  app_data:
  db_data:



